In [1]:
1

1

In [2]:
2

2

In [3]:
''""

''

In [4]:
'Hello world'

'Hello world'

In [5]:
1.2

1.2

In [6]:
4.8

4.8

In [7]:
True

True

In [8]:
False

False

In [9]:
x = 1

In [10]:
x

1

booleans

# 1. list

In [11]:
x = [1, 2, 3, "apple", True, [4, 5, 6]]

In [12]:
x

[1, 2, 3, 'apple', True, [4, 5, 6]]

In [13]:
x[0]

1

In [14]:
x[3]

'apple'

In [15]:
x[2] = 10

In [16]:
x

[1, 2, 10, 'apple', True, [4, 5, 6]]

In [17]:
x.append(100)

In [18]:
x

[1, 2, 10, 'apple', True, [4, 5, 6], 100]

In [21]:
x.insert(2, 300)

In [22]:
x

[1, 2, 300, 10, 'apple', True, [4, 5, 6], 100, 2]

In [23]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [24]:
help(list.pop)

Help on method_descriptor:

pop(self, index=-1, /)
    Remove and return item at index (default last).
    
    Raises IndexError if list is empty or index is out of range.



In [25]:
x

[1, 2, 300, 10, 'apple', True, [4, 5, 6], 100, 2]

In [26]:
x.pop()

2

In [27]:
x

[1, 2, 300, 10, 'apple', True, [4, 5, 6], 100]

In [32]:
len(x)

8

# 2. Tuple

In [30]:
# Creating a tuple
my_tuple = (1, 2, 3)
print("Tuple:", my_tuple)

# Accessing elements
print("First element:", my_tuple[0])
print("Second element:", my_tuple[1])
print("Third element:", my_tuple[2])

# Tuples can contain different data types
mixed_tuple = (1, "hello", 3.14)
print("Mixed Tuple:", mixed_tuple)

# Nested tuples
nested_tuple = (1, (2, 3), (4, 5, 6))
print("Nested Tuple:", nested_tuple)

# Tuples are immutable
# The following line would raise an error if uncommented
# my_tuple[0] = 10

# But we can concatenate tuples
concatenated_tuple = my_tuple + (4, 5, 6)
print("Concatenated Tuple:", concatenated_tuple)

# And we can repeat tuples
repeated_tuple = my_tuple * 2
print("Repeated Tuple:", repeated_tuple)

# Length of a tuple
print("Length of my_tuple:", len(my_tuple))

# Checking membership
print("Is 2 in my_tuple?", 2 in my_tuple)
print("Is 10 in my_tuple?", 10 in my_tuple)


Tuple: (1, 2, 3)
First element: 1
Second element: 2
Third element: 3
Mixed Tuple: (1, 'hello', 3.14)
Nested Tuple: (1, (2, 3), (4, 5, 6))
Concatenated Tuple: (1, 2, 3, 4, 5, 6)
Repeated Tuple: (1, 2, 3, 1, 2, 3)
Length of my_tuple: 3
Is 2 in my_tuple? True
Is 10 in my_tuple? False


In [31]:
my_tuple

(1, 2, 3)

# 3 Dict

In [33]:
# Creating a dictionary
my_dict = {
    "name": "Alice",
    "age": 25,
    "city": "New York"
}
print("Dictionary:", my_dict)

# Accessing values by keys
print("Name:", my_dict["name"])
print("Age:", my_dict["age"])
print("City:", my_dict["city"])

# Adding a new key-value pair
my_dict["email"] = "alice@example.com"
print("Dictionary after adding email:", my_dict)

# Updating an existing value
my_dict["age"] = 26
print("Dictionary after updating age:", my_dict)

# Removing a key-value pair
del my_dict["city"]
print("Dictionary after removing city:", my_dict)

# Using the get() method to access values
print("Name using get():", my_dict.get("name"))
print("City using get():", my_dict.get("city", "Not Found"))  # Provides a default value if the key is not found

# Checking if a key exists
print("Is 'name' a key in my_dict?", "name" in my_dict)
print("Is 'city' a key in my_dict?", "city" in my_dict)

# Iterating over keys
print("Keys in my_dict:")
for key in my_dict:
    print(key)

# Iterating over values
print("Values in my_dict:")
for value in my_dict.values():
    print(value)

# Iterating over key-value pairs
print("Key-value pairs in my_dict:")
for key, value in my_dict.items():
    print(key, ":", value)

# Getting the number of key-value pairs
print("Number of key-value pairs:", len(my_dict))


Dictionary: {'name': 'Alice', 'age': 25, 'city': 'New York'}
Name: Alice
Age: 25
City: New York
Dictionary after adding email: {'name': 'Alice', 'age': 25, 'city': 'New York', 'email': 'alice@example.com'}
Dictionary after updating age: {'name': 'Alice', 'age': 26, 'city': 'New York', 'email': 'alice@example.com'}
Dictionary after removing city: {'name': 'Alice', 'age': 26, 'email': 'alice@example.com'}
Name using get(): Alice
City using get(): Not Found
Is 'name' a key in my_dict? True
Is 'city' a key in my_dict? False
Keys in my_dict:
name
age
email
Values in my_dict:
Alice
26
alice@example.com
Key-value pairs in my_dict:
name : Alice
age : 26
email : alice@example.com
Number of key-value pairs: 3


# 4. NumPy

In [34]:
import numpy as np

In [36]:
a = np.array([1, 2, 3])

In [37]:
a

array([1, 2, 3])

In [38]:
a[0] = 100

In [39]:
a

array([100,   2,   3])

In [44]:
np.random.choice(a)

100

In [45]:
np.array([[1,2,3],[2,3,4]])

array([[1, 2, 3],
       [2, 3, 4]])

In [46]:
help(np.random.choice)

Help on built-in function choice:

choice(...) method of numpy.random.mtrand.RandomState instance
    choice(a, size=None, replace=True, p=None)
    
    Generates a random sample from a given 1-D array
    
    .. versionadded:: 1.7.0
    
    .. note::
        New code should use the `~numpy.random.Generator.choice`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    a : 1-D array-like or int
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated as if it were ``np.arange(a)``
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    replace : boolean, optional
        Whether the sample is with or without replacement. Default is True,
        meaning th

# 5. for loop

In [47]:
x

[1, 2, 300, 10, 'apple', True, [4, 5, 6], 100]

In [48]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [50]:
for i in range(1, 10):
    print(i)

1
2
3
4
5
6
7
8
9


In [51]:
x

[1, 2, 300, 10, 'apple', True, [4, 5, 6], 100]

In [52]:
for element in x:
    print(element)

1
2
300
10
apple
True
[4, 5, 6]
100


In [53]:
for i, element in enumerate(x):
    print(i, element)

0 1
1 2
2 300
3 10
4 apple
5 True
6 [4, 5, 6]
7 100


In [54]:
for i in range(len(x)):
    print(x[i])

1
2
300
10
apple
True
[4, 5, 6]
100


# 6. Conditionals

In [55]:
y = 5

In [56]:
if y > 8:
    print('hello')
else:
    print('Thank you')

Thank you


In [57]:
for i in range(len(x)):
    if i != 2:
        print(x[i])

1
2
10
apple
True
[4, 5, 6]
100


In [59]:
if y % 2 == 0:
    print('this is an even number')
else:
    print('this is an odd number')

this is an odd number
